package:
  name: splitfastq
  version: 0.0.1

source:
  path: .

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - pigz

test:
  commands:
    - splitFastq --help

about:
  home: https://github.com/maxplanck-ie/splitFastq
  license: MIT
  license_file: LICENSE
  summary: Splits the output of clumpify
